name: Build Compact Chat
on:
  - push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.0
        with:
          length: 7

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: graalvm
          java-version: 21

      - name: Upgrade Gradle
        run: ./gradlew wrapper --gradle-version=8.10.2 --distribution-type=bin # just hear me out okay, i dont want to dowwnload a whole IDE just for this

      - name: Setup Gradle
        uses: gradle/actions@v4.1.0

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Compact Chat Jar
        uses: actions/upload-artifact@v4.4.3
        with:
          name: CompactChat-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}
          path: build/libs/*.jar
